#!/usr/bin/perl 
# -*- tab-width: 4; mode: perl; -*-
#
# A hack to generate GPX files from the json generated by rid_capture.
#

use strict;
use JSON qw(decode_json);

my $operator  = "UNKNOWN";
my $timestamp = 0;
my $encoding  = ':encoding(UTF-8)';

my($a,$t,$o,$filename);
my($text,$file);
my($mac,$latitude,$longitude,$alt_msl,$heading,$speed,$operator,$timestamp);
my($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst,$zulu);
my($speed_ms,$name);
my(%handle);


while (<>) {

    $a = decode_json($_);

    $mac       = $$a{'mac'};
    $t         = $$a{'unix time'};
    $o         = $$a{'operator'};
    $latitude  = $$a{'uav latitude'};
    $longitude = $$a{'uav longitude'};
    $alt_msl   = $$a{'uav altitude'};
    $heading   = $$a{'uav heading'};
    $speed     = $$a{'uav speed'};

    if ($t) {
        $timestamp = $t;
    }

    if ($o) {
        $operator = $o;
    }
    
    if (($mac)&&($timestamp > 1000000)&&($latitude)&&($longitude)) {
    
        ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = gmtime($timestamp);
    
        $zulu      = sprintf("%04d-%02d-%02dT%02d:%02d:%02dZ",$year+1900,$mon+1,$mday,$hour,$min,$sec);
        $speed_ms  = $speed;

        $name      = ($operator) ? $operator: $mac;
    
        if (!$handle{$mac}) {

            $filename = "${mac}.gpx";
            $filename =~ s/\://g;

            print "$filename\n";
    
            open($handle{$mac},"> $encoding",$filename) || die "Cannot open ${filename}: $!";

            print_header($handle{$mac},$name);
        }

        $text  = sprintf("      <trkpt lat=\"%.6f\" lon=\"%.6f\">",$latitude,$longitude);
        $text .= "<time>${zulu}</time><ele>${alt_msl}</ele><speed>${speed_ms}</speed><course>${heading}</course></trkpt>\n";

        print_point($handle{$mac},$text);
    }
}

foreach $file (sort keys %handle) {

    print_footer($handle{$file});

    close $file;
}

#
#
#

sub print_header {

    my($file,$name) = @_;

    print $file <<EndOfHeader;
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<gpx 
  version="1.0"
  creator="RID Capture"
  author="Steve Jack"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns="http://www.topografix.com/GPX/1/1" 
  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd" >
  <name>$name</name>
  <trk>
    <name>$name</name>
    <trkseg>
EndOfHeader

}

#

sub print_point {

    my($file,$text) = @_;

    print $file $text;
}

#

sub print_footer {

    my($file) = @_;
    
    print $file <<EndOfFooter;
    </trkseg>
  </trk>
</gpx>
EndOfFooter

}

__END__
